deleted duplicated styles
vitsemashko/team-project-group-13 pull request #3
Opened 2022-09-08 18:58 UTC by AnastasiiaAAntonova

Пушу нову гілку, т.я. в попередню не підтягуюється ресет.
Прибрала зайві стилі, додала ховер - поки просто підкреслення

2022-09-08 19:57 UTC, vitsemashko commented
Дякую, зараз перегляну

2022-09-08 20:19 UTC, vitsemashko requested changes
Чудово, це вже близько до того, аби додати у main. Пропоную ще додати focus та спробувати додати transition для ховеру і фокусу, відповідно

2022-09-09 05:49 UTC, vitsemashko commented
Пропоную ще спробувати додати додаткові медіа-правила, щоб виглядало візуально краще від 1200 до 1440 рх

2022-09-09 11:08 UTC, AnastasiiaAAntonova commented
Додадала ховер і фокус - зміна кольору, transition та правило на мін-ширину 1200
Прошу перевірити.

Дякую.

2022-09-09 20:41 UTC, merged